/*
Even Fibonacci numbers
Problem 2

http://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

var myArray =[];
var mySum = 0;

function fibArray(limit) {
	var a = 1;
	var b = 2;
	var value = 2;

	while(value <= limit) {
		myArray.push(value);
		value = a+b;
		a = b;
		b = value;
	}

	return myArray;
}

function sumEven(){
	for(var i=0;i <= myArray.length; i++) {
		if (myArray[i]%2 === 0) {
			mySum += myArray[i];
		}
	}
	return mySum;
}

myArray = fibArray(4000000);
var solution = sumEven();

console.log('solution: ' + solution);
