/*
Even Fibonacci numbers
Problem 2

http://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

function isEven(value) {
	if(value%2 === 0) {
		return true;
	} else {
      return false;
    }
}

function fibonacci(value) {

	console.log('finbonacci: ' + value);

	if (value < 2 || value%2 !== 0) {
		return;
	} else {

		return (fibonacci(value-1) + fibonacci(value-2));
	}
}

var solution = fibonacci(12);

console.log('solution: ' + solution)
